# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TrainerViewWqxCKs.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_TrainerView(object):
    def setupUi(self, TrainerView):
        if not TrainerView.objectName():
            TrainerView.setObjectName(u"TrainerView")
        TrainerView.resize(900, 732)
        TrainerView.setMinimumSize(QSize(900, 732))
        TrainerView.setMaximumSize(QSize(900, 732))
        self.centralwidget = QWidget(TrainerView)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(900, 732))
        self.centralwidget.setMaximumSize(QSize(900, 732))
        self.sliderFrame = QFrame(self.centralwidget)
        self.sliderFrame.setObjectName(u"sliderFrame")
        self.sliderFrame.setGeometry(QRect(8, 8, 512, 301))
        self.sliderFrame.setFrameShape(QFrame.StyledPanel)
        self.sliderFrame.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget = QWidget(self.sliderFrame)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(-1, -1, 511, 301))
        self.sliderLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.sliderLayout.setSpacing(8)
        self.sliderLayout.setObjectName(u"sliderLayout")
        self.sliderLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.sliderLayout.setContentsMargins(0, 0, 0, 12)
        self.HSVRange = QFrame(self.verticalLayoutWidget)
        self.HSVRange.setObjectName(u"HSVRange")
        self.HSVRange.setFrameShape(QFrame.StyledPanel)
        self.HSVRange.setFrameShadow(QFrame.Raised)
        self.blank = QLabel(self.HSVRange)
        self.blank.setObjectName(u"blank")
        self.blank.setGeometry(QRect(0, 0, 48, 24))
        self.blank.setMargin(4)
        self.blank_2 = QLabel(self.HSVRange)
        self.blank_2.setObjectName(u"blank_2")
        self.blank_2.setGeometry(QRect(48, 0, 24, 24))
        self.label = QLabel(self.HSVRange)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(72, 0, 431, 24))
        self.label.setPixmap(QPixmap(u"Resources/hsv.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)

        self.sliderLayout.addWidget(self.HSVRange)

        self.lowHFrame = QFrame(self.verticalLayoutWidget)
        self.lowHFrame.setObjectName(u"lowHFrame")
        self.lowHFrame.setFrameShape(QFrame.StyledPanel)
        self.lowHFrame.setFrameShadow(QFrame.Raised)
        self.lowHSlider = QSlider(self.lowHFrame)
        self.lowHSlider.setObjectName(u"lowHSlider")
        self.lowHSlider.setGeometry(QRect(72, 0, 431, 24))
        self.lowHSlider.setMaximum(180)
        self.lowHSlider.setOrientation(Qt.Horizontal)
        self.lowHText = QLabel(self.lowHFrame)
        self.lowHText.setObjectName(u"lowHText")
        self.lowHText.setGeometry(QRect(0, 0, 48, 24))
        self.lowHText.setMargin(4)
        self.lowHValueText = QLabel(self.lowHFrame)
        self.lowHValueText.setObjectName(u"lowHValueText")
        self.lowHValueText.setGeometry(QRect(48, 0, 24, 24))

        self.sliderLayout.addWidget(self.lowHFrame)

        self.highHFrame = QFrame(self.verticalLayoutWidget)
        self.highHFrame.setObjectName(u"highHFrame")
        self.highHFrame.setFrameShape(QFrame.StyledPanel)
        self.highHFrame.setFrameShadow(QFrame.Raised)
        self.highHSlider = QSlider(self.highHFrame)
        self.highHSlider.setObjectName(u"highHSlider")
        self.highHSlider.setGeometry(QRect(72, 0, 431, 24))
        self.highHSlider.setMaximum(180)
        self.highHSlider.setValue(180)
        self.highHSlider.setOrientation(Qt.Horizontal)
        self.highHText = QLabel(self.highHFrame)
        self.highHText.setObjectName(u"highHText")
        self.highHText.setGeometry(QRect(0, 0, 48, 24))
        self.highHText.setMargin(4)
        self.highHValueText = QLabel(self.highHFrame)
        self.highHValueText.setObjectName(u"highHValueText")
        self.highHValueText.setGeometry(QRect(48, 0, 24, 24))

        self.sliderLayout.addWidget(self.highHFrame)

        self.separator1 = QFrame(self.verticalLayoutWidget)
        self.separator1.setObjectName(u"separator1")
        self.separator1.setFrameShadow(QFrame.Plain)
        self.separator1.setLineWidth(4)
        self.separator1.setFrameShape(QFrame.HLine)

        self.sliderLayout.addWidget(self.separator1)

        self.lowSFrame = QFrame(self.verticalLayoutWidget)
        self.lowSFrame.setObjectName(u"lowSFrame")
        self.lowSFrame.setFrameShape(QFrame.StyledPanel)
        self.lowSFrame.setFrameShadow(QFrame.Raised)
        self.lowSSlider = QSlider(self.lowSFrame)
        self.lowSSlider.setObjectName(u"lowSSlider")
        self.lowSSlider.setGeometry(QRect(72, 0, 431, 24))
        self.lowSSlider.setMaximum(255)
        self.lowSSlider.setOrientation(Qt.Horizontal)
        self.lowSText = QLabel(self.lowSFrame)
        self.lowSText.setObjectName(u"lowSText")
        self.lowSText.setGeometry(QRect(0, 0, 48, 24))
        self.lowSText.setMargin(4)
        self.lowSValueText = QLabel(self.lowSFrame)
        self.lowSValueText.setObjectName(u"lowSValueText")
        self.lowSValueText.setGeometry(QRect(48, 0, 24, 24))

        self.sliderLayout.addWidget(self.lowSFrame)

        self.highSFrame = QFrame(self.verticalLayoutWidget)
        self.highSFrame.setObjectName(u"highSFrame")
        self.highSFrame.setFrameShape(QFrame.StyledPanel)
        self.highSFrame.setFrameShadow(QFrame.Raised)
        self.highSSlider = QSlider(self.highSFrame)
        self.highSSlider.setObjectName(u"highSSlider")
        self.highSSlider.setGeometry(QRect(72, 0, 431, 24))
        self.highSSlider.setMaximum(255)
        self.highSSlider.setValue(255)
        self.highSSlider.setOrientation(Qt.Horizontal)
        self.highSText = QLabel(self.highSFrame)
        self.highSText.setObjectName(u"highSText")
        self.highSText.setGeometry(QRect(0, 0, 48, 24))
        self.highSText.setMargin(4)
        self.highSValueText = QLabel(self.highSFrame)
        self.highSValueText.setObjectName(u"highSValueText")
        self.highSValueText.setGeometry(QRect(48, 0, 24, 24))

        self.sliderLayout.addWidget(self.highSFrame)

        self.separator2 = QFrame(self.verticalLayoutWidget)
        self.separator2.setObjectName(u"separator2")
        self.separator2.setFrameShadow(QFrame.Plain)
        self.separator2.setLineWidth(4)
        self.separator2.setFrameShape(QFrame.HLine)

        self.sliderLayout.addWidget(self.separator2)

        self.lowVFrame = QFrame(self.verticalLayoutWidget)
        self.lowVFrame.setObjectName(u"lowVFrame")
        self.lowVFrame.setFrameShape(QFrame.StyledPanel)
        self.lowVFrame.setFrameShadow(QFrame.Raised)
        self.lowVSlider = QSlider(self.lowVFrame)
        self.lowVSlider.setObjectName(u"lowVSlider")
        self.lowVSlider.setGeometry(QRect(72, 0, 431, 24))
        self.lowVSlider.setMaximum(255)
        self.lowVSlider.setOrientation(Qt.Horizontal)
        self.lowVText = QLabel(self.lowVFrame)
        self.lowVText.setObjectName(u"lowVText")
        self.lowVText.setGeometry(QRect(0, 0, 48, 24))
        self.lowVText.setMargin(4)
        self.lowVValueText = QLabel(self.lowVFrame)
        self.lowVValueText.setObjectName(u"lowVValueText")
        self.lowVValueText.setGeometry(QRect(48, 0, 24, 24))

        self.sliderLayout.addWidget(self.lowVFrame)

        self.highVFrame = QFrame(self.verticalLayoutWidget)
        self.highVFrame.setObjectName(u"highVFrame")
        self.highVFrame.setFrameShape(QFrame.StyledPanel)
        self.highVFrame.setFrameShadow(QFrame.Raised)
        self.highVSlider = QSlider(self.highVFrame)
        self.highVSlider.setObjectName(u"highVSlider")
        self.highVSlider.setGeometry(QRect(72, 0, 431, 24))
        self.highVSlider.setMaximum(255)
        self.highVSlider.setValue(255)
        self.highVSlider.setOrientation(Qt.Horizontal)
        self.highVText = QLabel(self.highVFrame)
        self.highVText.setObjectName(u"highVText")
        self.highVText.setGeometry(QRect(0, 0, 48, 24))
        self.highVText.setMargin(4)
        self.highVValueText = QLabel(self.highVFrame)
        self.highVValueText.setObjectName(u"highVValueText")
        self.highVValueText.setGeometry(QRect(48, 0, 24, 24))

        self.sliderLayout.addWidget(self.highVFrame)

        self.separator1_2 = QFrame(self.verticalLayoutWidget)
        self.separator1_2.setObjectName(u"separator1_2")
        self.separator1_2.setFrameShadow(QFrame.Plain)
        self.separator1_2.setLineWidth(4)
        self.separator1_2.setFrameShape(QFrame.HLine)

        self.sliderLayout.addWidget(self.separator1_2)

        self.noiseReductionParam = QFrame(self.verticalLayoutWidget)
        self.noiseReductionParam.setObjectName(u"noiseReductionParam")
        self.noiseReductionParam.setFrameShape(QFrame.StyledPanel)
        self.noiseReductionParam.setFrameShadow(QFrame.Raised)
        self.noiseReductionParamSlider = QSlider(self.noiseReductionParam)
        self.noiseReductionParamSlider.setObjectName(u"noiseReductionParamSlider")
        self.noiseReductionParamSlider.setGeometry(QRect(152, 0, 351, 24))
        self.noiseReductionParamSlider.setMinimum(1)
        self.noiseReductionParamSlider.setSingleStep(2)
        self.noiseReductionParamSlider.setValue(5)
        self.noiseReductionParamSlider.setOrientation(Qt.Horizontal)
        self.noiseReductionParamText = QLabel(self.noiseReductionParam)
        self.noiseReductionParamText.setObjectName(u"noiseReductionParamText")
        self.noiseReductionParamText.setGeometry(QRect(0, 0, 121, 24))
        self.noiseReductionParamText.setMargin(4)
        self.noiseReductionParamValueText = QLabel(self.noiseReductionParam)
        self.noiseReductionParamValueText.setObjectName(u"noiseReductionParamValueText")
        self.noiseReductionParamValueText.setGeometry(QRect(128, 0, 21, 24))

        self.sliderLayout.addWidget(self.noiseReductionParam)

        self.image = QLabel(self.centralwidget)
        self.image.setObjectName(u"image")
        self.image.setGeometry(QRect(528, 8, 361, 232))
        self.image.setPixmap(QPixmap(u"../Resources/Templates/template-3.jpg"))
        self.image.setScaledContents(True)
        self.imageBinary = QLabel(self.centralwidget)
        self.imageBinary.setObjectName(u"imageBinary")
        self.imageBinary.setGeometry(QRect(528, 248, 361, 232))
        self.imageBinary.setPixmap(QPixmap(u"../Resources/Templates/template-3.jpg"))
        self.imageBinary.setScaledContents(True)
        self.imageBinaryEnhanced = QLabel(self.centralwidget)
        self.imageBinaryEnhanced.setObjectName(u"imageBinaryEnhanced")
        self.imageBinaryEnhanced.setGeometry(QRect(528, 488, 361, 232))
        self.imageBinaryEnhanced.setPixmap(QPixmap(u"../Resources/Templates/template-3.jpg"))
        self.imageBinaryEnhanced.setScaledContents(True)
        self.paramsControlFrame = QFrame(self.centralwidget)
        self.paramsControlFrame.setObjectName(u"paramsControlFrame")
        self.paramsControlFrame.setGeometry(QRect(8, 310, 511, 51))
        self.paramsControlFrame.setFrameShape(QFrame.StyledPanel)
        self.paramsControlFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget_3 = QWidget(self.paramsControlFrame)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(0, 0, 511, 51))
        self.paramsControlLayout = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.paramsControlLayout.setSpacing(4)
        self.paramsControlLayout.setObjectName(u"paramsControlLayout")
        self.paramsControlLayout.setContentsMargins(4, 0, 4, 0)
        self.saveParamsBtn = QPushButton(self.horizontalLayoutWidget_3)
        self.saveParamsBtn.setObjectName(u"saveParamsBtn")
        icon = QIcon()
        icon.addFile(u"Resources/arrow-down.png", QSize(), QIcon.Normal, QIcon.Off)
        self.saveParamsBtn.setIcon(icon)

        self.paramsControlLayout.addWidget(self.saveParamsBtn)

        self.resetParamsBtn = QPushButton(self.horizontalLayoutWidget_3)
        self.resetParamsBtn.setObjectName(u"resetParamsBtn")
        icon1 = QIcon()
        icon1.addFile(u"Resources/undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.resetParamsBtn.setIcon(icon1)
        self.resetParamsBtn.setIconSize(QSize(18, 18))

        self.paramsControlLayout.addWidget(self.resetParamsBtn)

        self.useImgBtn = QPushButton(self.horizontalLayoutWidget_3)
        self.useImgBtn.setObjectName(u"useImgBtn")
        self.useImgBtn.setEnabled(True)
        icon2 = QIcon()
        icon2.addFile(u"Resources/upload.png", QSize(), QIcon.Normal, QIcon.Off)
        self.useImgBtn.setIcon(icon2)
        self.useImgBtn.setIconSize(QSize(18, 18))

        self.paramsControlLayout.addWidget(self.useImgBtn)

        self.useCameraBtn = QPushButton(self.horizontalLayoutWidget_3)
        self.useCameraBtn.setObjectName(u"useCameraBtn")
        self.useCameraBtn.setEnabled(False)
        icon3 = QIcon()
        icon3.addFile(u"Resources/camera-lens.png", QSize(), QIcon.Normal, QIcon.Off)
        self.useCameraBtn.setIcon(icon3)
        self.useCameraBtn.setIconSize(QSize(18, 18))

        self.paramsControlLayout.addWidget(self.useCameraBtn)

        self.savedParamsFrame = QFrame(self.centralwidget)
        self.savedParamsFrame.setObjectName(u"savedParamsFrame")
        self.savedParamsFrame.setGeometry(QRect(8, 364, 511, 91))
        self.savedParamsFrame.setFrameShape(QFrame.StyledPanel)
        self.savedParamsFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget_2 = QWidget(self.savedParamsFrame)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 0, 511, 91))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.lowRedValueTextBtn = QPushButton(self.horizontalLayoutWidget_2)
        self.lowRedValueTextBtn.setObjectName(u"lowRedValueTextBtn")
        self.lowRedValueTextBtn.setEnabled(False)
        self.lowRedValueTextBtn.setMaximumSize(QSize(16777215, 72))
        font = QFont()
        font.setFamily(u"Franklin Gothic Heavy")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lowRedValueTextBtn.setFont(font)
        self.lowRedValueTextBtn.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.lowRedValueTextBtn)

        self.highRedValueTextBtn = QPushButton(self.horizontalLayoutWidget_2)
        self.highRedValueTextBtn.setObjectName(u"highRedValueTextBtn")
        self.highRedValueTextBtn.setEnabled(True)
        self.highRedValueTextBtn.setMaximumSize(QSize(16777215, 72))
        font1 = QFont()
        font1.setFamily(u"Franklin Gothic Heavy")
        font1.setPointSize(10)
        self.highRedValueTextBtn.setFont(font1)

        self.horizontalLayout.addWidget(self.highRedValueTextBtn)

        self.commandsFrame = QFrame(self.centralwidget)
        self.commandsFrame.setObjectName(u"commandsFrame")
        self.commandsFrame.setGeometry(QRect(8, 670, 511, 51))
        self.commandsFrame.setFrameShape(QFrame.StyledPanel)
        self.commandsFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget = QWidget(self.commandsFrame)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 511, 51))
        self.commandsLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.commandsLayout.setSpacing(8)
        self.commandsLayout.setObjectName(u"commandsLayout")
        self.commandsLayout.setContentsMargins(8, 8, 8, 8)
        self.closeBtn = QPushButton(self.horizontalLayoutWidget)
        self.closeBtn.setObjectName(u"closeBtn")
        icon4 = QIcon()
        icon4.addFile(u"Resources/delete-button.png", QSize(), QIcon.Normal, QIcon.Off)
        self.closeBtn.setIcon(icon4)

        self.commandsLayout.addWidget(self.closeBtn)

        TrainerView.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainerView)

        QMetaObject.connectSlotsByName(TrainerView)
    # setupUi

    def retranslateUi(self, TrainerView):
        TrainerView.setWindowTitle(QCoreApplication.translate("TrainerView", u"MainWindow", None))
        self.blank.setText("")
        self.blank_2.setText("")
        self.label.setText("")
        self.lowHText.setText(QCoreApplication.translate("TrainerView", u"Low H", None))
        self.lowHValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.highHText.setText(QCoreApplication.translate("TrainerView", u"High H", None))
        self.highHValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.lowSText.setText(QCoreApplication.translate("TrainerView", u"Low S", None))
        self.lowSValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.highSText.setText(QCoreApplication.translate("TrainerView", u"High S", None))
        self.highSValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.lowVText.setText(QCoreApplication.translate("TrainerView", u"Low V", None))
        self.lowVValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.highVText.setText(QCoreApplication.translate("TrainerView", u"High V", None))
        self.highVValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.noiseReductionParamText.setText(QCoreApplication.translate("TrainerView", u"Noise Reduction Param", None))
        self.noiseReductionParamValueText.setText(QCoreApplication.translate("TrainerView", u"0", None))
        self.image.setText("")
        self.imageBinary.setText("")
        self.imageBinaryEnhanced.setText("")
        self.saveParamsBtn.setText(QCoreApplication.translate("TrainerView", u" Save", None))
        self.resetParamsBtn.setText(QCoreApplication.translate("TrainerView", u" Reset", None))
        self.useImgBtn.setText(QCoreApplication.translate("TrainerView", u" Use Image", None))
        self.useCameraBtn.setText(QCoreApplication.translate("TrainerView", u" Use Camera", None))
        self.lowRedValueTextBtn.setText(QCoreApplication.translate("TrainerView", u"LOW RED [0, 0, 0] [30, 255, 255]", None))
        self.highRedValueTextBtn.setText(QCoreApplication.translate("TrainerView", u"HIGH RED [150, 0, 0] [180, 255, 255]", None))
        self.closeBtn.setText(QCoreApplication.translate("TrainerView", u" Close", None))
    # retranslateUi

